// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUNOye9vZWFQLpNxHISP8xiYW7xYScojg',
    appId: '1:295938916012:web:ed59622a0c912d0d19e909',
    messagingSenderId: '295938916012',
    projectId: 'pulse-c1811',
    authDomain: 'pulse-c1811.firebaseapp.com',
    storageBucket: 'pulse-c1811.firebasestorage.app',
    measurementId: 'G-SCZWYF1X6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGTtciYLN2nIrEXOG8hDRa-uSnCi9nueo',
    appId: '1:295938916012:android:d17485b79bcc4c6119e909',
    messagingSenderId: '295938916012',
    projectId: 'pulse-c1811',
    storageBucket: 'pulse-c1811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7X34Kj00oCcrsT9jg_TqMiifqYAomiZc',
    appId: '1:295938916012:ios:59e2fbd7b9c1b22d19e909',
    messagingSenderId: '295938916012',
    projectId: 'pulse-c1811',
    storageBucket: 'pulse-c1811.firebasestorage.app',
    iosBundleId: 'com.example.pulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7X34Kj00oCcrsT9jg_TqMiifqYAomiZc',
    appId: '1:295938916012:ios:59e2fbd7b9c1b22d19e909',
    messagingSenderId: '295938916012',
    projectId: 'pulse-c1811',
    storageBucket: 'pulse-c1811.firebasestorage.app',
    iosBundleId: 'com.example.pulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUNOye9vZWFQLpNxHISP8xiYW7xYScojg',
    appId: '1:295938916012:web:c93c85ef1980cb2c19e909',
    messagingSenderId: '295938916012',
    projectId: 'pulse-c1811',
    authDomain: 'pulse-c1811.firebaseapp.com',
    storageBucket: 'pulse-c1811.firebasestorage.app',
    measurementId: 'G-EBYB4VX0DV',
  );
}
